### ISSUE TITLE
Offline accounts cannot be modified via /eco

### ISSUE THREAD

**Issue by ZachyFoxx** [DumbDogDiner/StickyWallet#13]
Accounts cannot be modified (found) by the /eco command (e.g. /eco set notzachery 0) if the casing of the username is wrong

**To Reproduce**
1. Have an offline account setup
2. Type '/eco take notzachery 1 currency'

**Expected behavior**
1 currency should be taken away from notzachery regardless of casing

**Actual behavior**
The specific player could not be found due to the casing being wrong

**Comment by vladfrangu** [comment]
Whats the message you get?

**Comment by ZachyFoxx** [comment]
> Whats the message you get?

The specified player does not exist or could not be found

After some testing, it's case-sensitive, i'll update the issue

**Comment by vladfrangu** [comment]
Not a bug, names are case sensitive in Minecraft, the fact I let you auto complete with case insensitivity is my choice... Use tab completion based on search queries (names are returned directly from the accounts table)

**Comment by ZachyFoxx** [comment]
> Not a bug, names are case sensitive in Minecraft, the fact I let you auto complete with case insensitivity is my choice... Use tab completion based on search queries (names are returned directly from the accounts table)

Consider using String#equals(String, true) to solve this, even if Minecraft is case sensitive, your plugin does not have to be.

**Comment by vladfrangu** [comment]
My plugin already does does case insensitivity filtering (you can see by the fact `notz` returns `NotZachery` in game). I will stick to Minecraft's case sensitivity when it comes to saving in the DB, and referencing afterwards, as it's the most correct, and otherwise would require me to save lowercased names in the DB which can conflict. As I said, once you matched your name via search queries, press tab

This is a feature request more than anything btw, not a bug 😄
